openapi: "3.0.3"
info:
  title: API eventos
  version: "1.0.0"
  description: API para eventos
tags:
  - name: eventos
    description: Operaciones con eventos
paths:
  "/api/eventos":
    get:
      tags:
        - eventos
      summary: Obtener los eventos del mes
      operationId: getEventosDelMes
      parameters:
        - name: month
          in: query
          required: true
          description: Mes de los eventos a obtener
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - name: year
          in: query
          required: true
          description: Año de los eventos a obtener
          schema:
            type: integer
      responses:
        "200":
          description: Eventos obtenidos
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/ListadoEventoDTO"
        "400":
          description: Parámetros inválidos
          $ref: "#/components/responses/BadRequest"
        "500":
          description: Error interno del servidor
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - eventos
      summary: Crear evento
      operationId: crearEvento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrearEventoDTO"
      responses:
        "201":
          description: Evento creado
          headers:
            location:
              description: URL del evento creado
              schema:
                type: string
                format: uri
        "400":
          description: Parámetros inválidos
          $ref: "#/components/responses/BadRequest"
        "500":
          description: Error interno del servidor
          $ref: "#/components/responses/InternalServerError"
  "/api/eventos/{id}":
    get:
      tags:
        - eventos
      summary: recuperar evento
      operationId: recuperarEvento
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador del evento
          schema:
            type: string
      responses:
        "200":
          description: Evento obtenido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventoDTO"
        "404":
          description: Evento no encontrado
          $ref: "#/components/responses/NotFound"
        "500":
          description: Error interno del servidor
          $ref: "#/components/responses/InternalServerError"
    patch:
      tags:
        - eventos
      summary: Actualizacion parcial de un evento
      operationId: modificarEvento
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador del evento
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModificarEventoDTO"
      responses:
        "204":
          description: Evento modificado
        "400":
          description: Parámetros inválidos
          $ref: "#/components/responses/BadRequest"
        "404":
          description: Evento o Espacio Físico no encontrado
          $ref: "#/components/responses/NotFound"
        "500":
          description: Error interno del servidor
          $ref: "#/components/responses/InternalServerError"
  "/api/eventos/{id}/ocupacion":
    put:
      tags:
        - eventos
      summary: cancelar un evento
      operationId: cancelarEvento
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador del evento
          schema:
            type: string
      responses:
        "204":
          description: Evento cancelado
        "404":
          description: Evento no encontrado
          $ref: "#/components/responses/NotFound"
        "500":
          description: Error interno del servidor
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    CategoriaDTO:
      type: string
      description: Categoría del evento
      enum:
        - ACADÉMICOS
        - CULTURAL
        - ENTRETENIMIENTO
        - DEPORTES
        - OTROS
    ListadoEventoDTO:
      type: object
      properties:
        eventos:
          type: array
          items:
            $ref: "#/components/schemas/ItemEventoDTO"
    ItemEventoDTO:
      type: object
      properties:
        uri:
          type: string
          format: uri
          description: URI del evento
        evento:
          $ref: "#/components/schemas/EventoDTO"
    EventoDTO:
      type: object
      properties:
        id:
          type: string
          description: Identificador del evento
        nombre:
          type: string
          description: Nombre del evento
        descripcion:
          type: string
          description: Descripción del evento
        organizador:
          type: string
          description: Organizador del evento
        categoria:
          $ref: "#/components/schemas/CategoriaDTO"
        fechaInicio:
          type: string
          format: date-time
          description: Fecha de inicio del evento
        fechaFin:
          type: string
          format: date-time
          description: Fecha de fin del evento
        plazas:
          type: integer
          description: Número de plazas requeridas
        idEspacioFisico:
          type: string
          description: Identificador del espacio físico que se va a utilizar para el evento
    CrearEventoDTO:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del evento
        descripcion:
          type: string
          description: Descripción del evento
        organizador:
          type: string
          description: Organizador del evento
        categoria:
          $ref: "#/components/schemas/CategoriaDTO"
        fechaInicio:
          type: string
          format: date-time
          description: Fecha de inicio del evento
        fechaFin:
          type: string
          format: date-time
          description: Fecha de fin del evento
        plazas:
          type: integer
          description: Número de plazas requeridas
        idEspacioFisico:
          type: string
          description: Identificador del espacio físico que se va a utilizar para el evento
    ModificarEventoDTO:
      type: object
      properties:
        descripcion:
          type: string
          description: nueva descripción del evento
        fechaInicio:
          type: string
          format: date-time
          description: nueva fecha de inicio del evento
        fechaFin:
          type: string
          format: date-time
          description: nueva fecha de fin del evento
        plazas:
          type: integer
          description: nuevo número de plazas requeridas
        idEspacioFisico:
          type: string
          description: nuevo identificador del espacio físico que se va a utilizar para el evento
    ProblemDetail:
      description: A problemDetail Details object
      type: object
      additionalProperties: true
      properties:
        title:
          type: string
          maxLength: 500
          description: A short summary of the problem
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: The HTTP Status Code generated by the origin server for this occurrence of the problem
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          maxLength: 5000
          description: A human-readable explanation specific to this occurrence of the problem
          example: Requested service not available
        instance:
          type: string
          maxLength: 2000
          description: URI reference that identifies the specific occurrence of the problem
          example: /eventos
      example:
        title: Bad Request
        status: 400
        detail: Requested service not available
        instance: /eventos
  responses:
    BadRequest:
      description: "Bad request. One or more parameters has an invalid value."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
          example:
            type: about:blank
            title: Bad Request
            status: 400
            detail: The request could not be understood by the server due to malformed syntax
            instance: /eventos
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
          example:
            type: about:blank
            title: Not Found
            status: 404
            detail: The requested resource could not be found
            instance: /api/eventos
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
          example:
            type: about:blank
            title: Internal Server Error
            status: 500
            detail: The server encountered an unexpected condition
            instance: /iopcljava/v1/eventos
