services:
  gateway-app:
    build: ./gateway
    container_name: gateway-app
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - eventos-app
      - reservas-app
      - espacios-app
      - mysql-db
      - mongo-db
      - rabbitmq
    networks:
      - arso-net
  espacios-app:
    build: ./espacios
    container_name: espacios-app
    restart: always
    depends_on:
      - mysql-db
      - rabbitmq
    networks:
      - arso-net
  eventos-app:
    build: ./eventos
    container_name: eventos-app
    restart: always
    depends_on:
      - mysql-db
      - rabbitmq
    networks:
      - arso-net
  reservas-app:
    build: ./reservas
    container_name: reservas-app
    restart: always
    depends_on:
      - mongo-db
      - rabbitmq
    networks:
      - arso-net
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./.mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: practicas
    networks:
      - arso-net
  mongo-db:
    image: mongo:5.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo-data/:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: practicas
      MONGO_INITDB_DATABASE: arso
    networks:
      - arso-net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: practicas
      ME_CONFIG_MONGODB_URL: mongodb://root:practicas@mongo-db:27017/
    depends_on:
      - mongo-db
    networks:
      - arso-net
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: arso
      RABBITMQ_DEFAULT_PASS: practicas
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
    networks:
      - arso-net
networks:
  arso-net:
    driver: bridge
